### PR TITLE
Upgrading stats connector

### PR DESCRIPTION
**Pull request by glitchassassin**
The current stats connector complains about a certificate error connecting to screeps.com. This seems to be an issue with the ancient version of Node that it requires. I rewrote the script to use a modern version of Node instead and this has resolved the issue.

This also introduces a SCREEPS_HOST variable in the docker-compose.env file to allow connecting to private servers.

### CODE REVIEW

**Comment by Morningtea7** [comment]
Since you changed the port to 1338, the port specified in `setup.sh` should also be updated.

**Comment by glitchassassin** [comment]
Thanks, I had that changed in my setup to avoid a local conflict but intended to leave it at 1337. Should be corrected in the docker-compose now

**Comment by glitchassassin** [comment]
@AlinaNova21 Any interest in this PR?

**Comment by new-guy** [comment]
Appreciate you putting this together - found it by searching in discord and it fixed my issues!

**Pull request merged**
