### PR TITLE
allows to store stats as a structured object ingame

### PR DESCRIPTION
**Pull request by thibaut-fagart**
It allows for less memory usage (no need to duplicate the parent object paths for every stat)

### CODE REVIEW

**Comment by theCapypara** [comment]
But this doesn't work.
k and v are both undefined. I just noticed this while trying to implement custom server support.

**Comment by theCapypara** [comment]
The actual code has to be
```coffeescript
  report: (data, prefix="") =>
    if prefix is ''
      console.log "Pushing to gauges - " + new Date()
      for k,v of data
        if typeof v is 'object'
          @report(v, prefix+k+'.')
        else
          @client.gauge prefix+k, v
```

**Comment by thibaut-fagart** [comment]
you're right ... i did a bad copy paste when pushing my change to github (hadn't set up git upstream from my ec2 :( )

**Comment by theCapypara** [comment]
It's okay, I was just confused this went unnoticed since September :O

**Pull request merged**
